# Project metadata
sonar.projectKey=ganesh-app
sonar.projectName=Ganesh App

# Source and build paths
sonar.sources=src
sonar.java.binaries=target/classes

# Encoding (optional but recommended)
sonar.sourceEncoding=UTF-8

# Language (optional - defaults to Java)
sonar.language=java
