apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxNzIuMzEuMTAuMjI0OjMwODAwIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6ImFkbWluMTIzIiwiZW1haWwiOiJ5b3VAZXhhbXBsZS5jb20iLCJhdXRoIjoiWVdSdGFXNDZZV1J0YVc0eE1qTT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: nexus-secret
type: kubernetes.io/dockerconfigjson
